name: microproject-simulation-for-ten-heads-in-a-row Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-simulation-for-ten-heads-in-a-row/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v4
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-simulation-for-ten-heads-in-a-row
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v4
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Copy up-to-date grading files from release
      id: local-copy
      uses: illinois/local-copy@v2
      with:
        src_path: release/microproject-simulation-for-ten-heads-in-a-row
        dst_path: microproject-simulation-for-ten-heads-in-a-row
        copy: '.github/classroom : .github/classroom, requirements.txt : requirements.txt'
    - run: pip install -r microproject-simulation-for-ten-heads-in-a-row/requirements.txt
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-simulation-for-ten-heads-in-a-row/microproject-simulation-for-ten-heads-in-a-row.ipynb release/microproject-simulation-for-ten-heads-in-a-row/microproject-simulation-for-ten-heads-in-a-row.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-simulation-for-ten-heads-in-a-row/microproject-simulation-for-ten-heads-in-a-row.ipynb "### TEST CASE for (.*)" microproject-simulation-for-ten-heads-in-a-row/test_microproject-simulation-for-ten-heads-in-a-row.py '
    - name: Generate Grading Artifacts
      run: cd microproject-simulation-for-ten-heads-in-a-row && python3 test_microproject-simulation-for-ten-heads-in-a-row.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v5
      with:
        path: microproject-simulation-for-ten-heads-in-a-row/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
