name: microproject-choropleth-map-dataframe Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-choropleth-map-dataframe/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-choropleth-map-dataframe
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Copy up-to-date grading files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/microproject-choropleth-map-dataframe
        dst_path: microproject-choropleth-map-dataframe
        copy: '.github/classroom : .github/classroom, requirements.txt : requirements.txt'
    - run: pip install -r microproject-choropleth-map-dataframe/requirements.txt
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-choropleth-map-dataframe/microproject-choropleth-map-dataframe.ipynb release/microproject-choropleth-map-dataframe/microproject-choropleth-map-dataframe.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-choropleth-map-dataframe/microproject-choropleth-map-dataframe.ipynb "### TEST CASE for (.*)" microproject-choropleth-map-dataframe/test_microproject-choropleth-map-dataframe.py '
    - name: Generate Grading Artifacts
      run: cd microproject-choropleth-map-dataframe && python3 test_microproject-choropleth-map-dataframe.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v4
      with:
        path: microproject-choropleth-map-dataframe/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
