name: microproject-illini-football-scores Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-illini-football-scores/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-illini-football-scores
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Copy up-to-date grading files from release
      id: local-copy
      uses: illinois/local-copy@v1
      with:
        src_path: release/microproject-illini-football-scores
        dst_path: microproject-illini-football-scores
        copy: '.github/classroom : .github/classroom, requirements.txt : requirements.txt'
    - run: pip install -r microproject-illini-football-scores/requirements.txt
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-illini-football-scores/microproject-illini-football-scores.ipynb release/microproject-illini-football-scores/microproject-illini-football-scores.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-illini-football-scores/microproject-illini-football-scores.ipynb "### TEST CASE for (.*)" microproject-illini-football-scores/test_microproject-illini-football-scores.py '
    - name: Generate Grading Artifacts
      run: cd microproject-illini-football-scores && python3 test_microproject-illini-football-scores.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v4
      with:
        path: microproject-illini-football-scores/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
