name: microproject-united-nations-refugee-data Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-united-nations-refugee-data/requirements.txt
    - run: pip install -r microproject-united-nations-refugee-data/requirements.txt
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: microproject-united-nations-refugee-data/
        test_suite: autograding
        step_summary: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
