name: microproject-world-university-rankings Grading
'on':
  workflow_dispatch: {}
permissions:
  actions: write
  contents: read
  checks: read
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: microproject-world-university-rankings/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v4
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-world-university-rankings
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v4
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Copy up-to-date grading files from release
      id: local-copy
      uses: illinois/local-copy@v2
      with:
        src_path: release/microproject-world-university-rankings
        dst_path: microproject-world-university-rankings
        copy: '.github/classroom : .github/classroom, requirements.txt : requirements.txt'
    - run: pip install -r microproject-world-university-rankings/requirements.txt
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-world-university-rankings/microproject-world-university-rankings.ipynb release/microproject-world-university-rankings/microproject-world-university-rankings.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-world-university-rankings/microproject-world-university-rankings.ipynb "### TEST CASE for (.*)" microproject-world-university-rankings/test_microproject-world-university-rankings.py '
    - name: Generate Grading Artifacts
      run: cd microproject-world-university-rankings && python3 test_microproject-world-university-rankings.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v6
      with:
        path: microproject-world-university-rankings/
        test_suite: autograding
        step_summary: true
    - name: Log telemetry data
      uses: illinois/telemetry@dev_zojize
      with:
        endpoint: http://141.142.220.106:10710/telemetry
        log_date: true
        assignment: microproject-world-university-rankings
        upstream_repo: dsdiscovery/microprojects
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
